services:
  caddy:
    image: caddy:latest
    container_name: caddy
    restart: unless-stopped
    volumes:
      - ./data/caddy:/data/caddy
      - ./config/caddy:/etc/caddy
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 80:80
      - 443:443

  headscale:
    image: headscale/headscale:latest
    container_name: headscale
    restart: unless-stopped
    command: serve
    volumes:
      - ./data/headscale:/var/lib/headscale
      - ./config/headscale:/etc/headscale
    environment:
      TZ: Europe/Ljubljana
  
  #headboard:
  #  image: ghcr.io/krofek/headboard:main
  #  container_name: headboard
  #  restart: unless-stopped
  #  environment:
  #    TZ: Europe/Ljubljana

  headscale-admin:
    image: ghcr.io/krofek/headscale-admin:main
    container_name: headscale-admin
    restart: unless-stopped
    environment:
      TZ: Europe/Ljubljana

